module.exports = {
  prefix: "revdoc",
  prefixIRI: "https://valospace.org/revdoc#",

  prefixes: {
    revdoc: "https://valospace.org/revdoc#",
  },
  context: {
  },
  vocabulary: {
    Document: { a: "rdfs:Class", "rdfs:subClassOf": "vdoc:Chapter",
      "rdfs:comment": "A ReSpec specification document",
    },
    Definition: { a: "rdfs:Class", "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A ReSpec term definition document node",
    },
    Package: { a: "rdfs:Class", "rdfs:subClassOf": "vdoc:Reference",
      "rdfs:comment": "A package reference document node",
    },
    Command: { a: "rdfs:Class", "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A command invokation document node",
    },
    CommandLineInteraction: { a: "rdfs:Class", "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A command line interaction sequence document node",
    },
    prefix: { a: "rdf:Property",
      "rdfs:domain": "revdoc:Document", "rdfs:range": "rdfs:Literal",
      "rdfs:comment": "The preferred prefix of an ontology document",
    },
    prefixIRI: { a: "rdf:Property",
      "rdfs:domain": "revdoc:Document", "rdfs:range": "rdfs:Resource",
      "rdfs:comment": "The IRI associated with the preferred prefix of an ontology",
    },
    package: { a: "rdf:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Literal",
      "rdfs:comment": "A package name",
    },
    version: { a: "rdf:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Literal",
      "rdfs:comment": "A semver string",
    },
  },
  extractionRules: {
    ontology: {
      range: "vdoc:Chapter", owner: "vdoc:content", body: "vdoc:content", rest: "dc:title",
      comment: "Ontology specification chapter",
    },
  },
};
