const { createOntology } = require("@valos/vdoc");

module.exports = createOntology("revdoc", "https://valospace.org/revdoc#", {
  prefixes: {
    revdoc: "https://valospace.org/revdoc#",
  },
  vocabulary: {
    Document: { "@type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Chapter",
      "rdfs:comment": "A ReSpec specification document",
    },
    Definition: { "@type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A ReSpec term definition document node",
    },
    Package: { "@type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Reference",
      "rdfs:comment": "A package reference document node",
    },
    Command: { "@type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A command invokation document node",
    },
    CommandLineInteraction: { "@type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A command line interaction sequence document node",
    },
    prefix: { "@type": "vdoc:Property",
      "rdfs:domain": "revdoc:Document", "rdfs:range": "rdfs:Literal",
      "rdfs:comment": "The preferred prefix of an ontology document",
    },
    prefixIRI: { "@type": "vdoc:Property",
      "rdfs:domain": "revdoc:Document", "rdfs:range": "rdfs:Resource",
      "rdfs:comment": "The IRI associated with the preferred prefix of an ontology",
    },
    package: { "@type": "vdoc:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Literal",
      "rdfs:comment": "A package name",
    },
    version: { "@type": "vdoc:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Literal",
      "rdfs:comment": "A semver string",
    },
  },
  extractionRules: {
    ontology: {
      range: "vdoc:Chapter", owner: "vdoc:content", body: "vdoc:content", rest: "dc:title",
      comment: "Ontology specification chapter",
    },
  },
});
