const extendOntology = require("./extendOntology");

const htmlSpecBase = "https://html.spec.whatwg.org/multipage/";
const prefixes = {
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
  rdfs: "http://www.w3.org/2000/01/rdf-schema#",
  xsd: "http://www.w3.org/2001/XMLSchema#",
  owl: "http://www.w3.org/2002/07/owl#",
  dc: "http://purl.org/dc/elements/1.1/",
};

module.exports = extendOntology("VDoc", "https://valospace.org/vdoc/0#", prefixes, {
  Class: { "@type": ["VDoc:Class", "VKernel:Class"],
    "rdfs:subClassOf": "rdfs:Class",
    "rdfs:comment": "The class of classes which are defined by vdoc or a vdoc extension",
  },
  Property: { "@type": ["VDoc:Class", "VKernel:Class"],
    "rdfs:subClassOf": "rdf:Property",
    "rdfs:comment": "The class of properties which are defined by vdoc or a vdoc extension",
  },
  Node: { "@type": "VDoc:Class",
    "rdfs:comment": "A document tree Node",
  },
  resourceId: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "xsd:string",
    "rdfs:comment": "The resource identifier of a resource node",
  },
  content: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:List",
    "rdfs:comment": "The primary visible content of a Node",
  },
  words: { "@type": "VDoc:Property",
    "rdfs:subPropertyOf": "VDoc:content",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:List",
    "rdfs:comment": "A visible list of visually separate words",
  },
  entries: { "@type": "VDoc:Property",
    "rdfs:subPropertyOf": "VDoc:content",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:List",
    "rdfs:comment": "A visible list of vertically or horizontally segmented entries",
  },
  lookup: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "rdfs:comment": "A reference to a lookup structure for string literal entries",
  },
  wide: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "rdfs:comment": "Marks the node content as being wide",
  },
  tall: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "rdfs:comment": "Marks the node content as being tall",
  },
  Chapter: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A titled, possibly numbered chapter document node",
  },
  Paragraph: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A vertically segmented paragraph document node",
  },
  BulletList: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A bullet list document node",
  },
  NumberedList: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A numbered list document node",
  },
  Table: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A two-dimensional table document node",
  },
  Header: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A table cross-entry-section header node",
  },
  headers: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:Table",
    "rdfs:range": "rdfs:List",
    "rdfs:comment": "A list of table cross-entry-section headers",
  },
  cell: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:Header",
    "rdfs:range": "rdfs:List",
    "rdfs:comment": "The template for building cell content using content selectors",
  },
  ContentSelector: { "@type": "VDoc:Class",
    "rdfs:comment": "The class of selectors with explicit meaning for selecting content",
  },
  selectKey: { "@type": "VDoc:ContentSelector",
    "rdfs:comment": "A content selector literal denoting the entry lookup key",
  },
  selectValue: { "@type": "VDoc:ContentSelector",
    "rdfs:comment": "A content selector literal denoting the whole entry value",
  },
  selectField: { "@type": "VDoc:Property",
    "rdfs:domain": "rdfs:Resource",
    "rdfs:range": "rdfs:Literal",
    "rdfs:comment": "A content selector for the entry field denoted by the object of this triple",
  },
  CharacterData: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A character data document node",
  },
  language: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:CharacterData",
    "rdfs:range": "rdfs:Resource",
    "rdfs:comment": "The language of the character data content",
  },
  Reference: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A reference document node",
  },
  ContextPath: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Node",
    "rdfs:comment": "A context-based path document node",
  },
  context: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:ContextPath",
    "rdfs:range": "rdfs:Resource",
    "rdfs:comment": "Non-visible context base (absolute or relative to current base)",
  },
  ContextBase: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:ContextPath",
    "rdfs:comment": "A context base setting document node",
  },
  HTMLElementProperty: { "@type": "VDoc:Class",
    "rdfs:subClassOf": "VDoc:Property",
    "rdfs:comment":
`The class of vdoc properties which directly inherit the semantics of a specific HTML5 element`,
  },
  elementName: { "@type": "VDoc:Property",
    "rdfs:domain": "VDoc:HTMLElementProperty",
    "rdfs:range": "xsd:string",
    "rdfs:comment": "The name of the html element associated with this property",
  },
  em: { "@type": "VDoc:HTMLElementProperty",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "VDoc:elementName": "em",
    "VDoc:elementSpec": `${htmlSpecBase}text-level-semantics.html#the-em-element`,
    "rdfs:comment": "Node content is <em>emphasised</em>",
  },
  strong: { "@type": "VDoc:HTMLElementProperty",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "VDoc:elementName": "strong",
    "VDoc:elementSpec": `${htmlSpecBase}text-level-semantics.html#the-strong-element`,
    "rdfs:comment": "Node content is <strong>strong</strong>",
  },
  ins: { "@type": "VDoc:HTMLElementProperty",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "VDoc:elementName": "ins",
    "VDoc:elementSpec": `${htmlSpecBase}edits.html#the-ins-element`,
    "rdfs:comment": "Node content is an <ins>insertion</ins>",
  },
  del: { "@type": "VDoc:HTMLElementProperty",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "VDoc:elementName": "del",
    "VDoc:elementSpec": `${htmlSpecBase}edits.html#the-del-element`,
    "rdfs:comment": "Node content is <del>deleted</del>",
  },
  quote: { "@type": "VDoc:HTMLElementProperty",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "VDoc:elementName": "quote",
    "VDoc:elementSpec": `${htmlSpecBase}text-level-semantics.html#the-q-element`,
    "rdfs:comment": "Node content is <q>quoted</q>",
  },
  blockquote: { "@type": "VDoc:HTMLElementProperty",
    "rdfs:domain": "VDoc:Node",
    "rdfs:range": "rdfs:Resource",
    "VDoc:elementName": "blockquote",
    "VDoc:elementSpec": `${htmlSpecBase}grouping-content.html#the-blockquote-element`,
    "rdfs:comment": "Node content is <blockquote>block quoted</blockquote>",
  },
}, {
  extractionRules: {
    "": {
      comment: "Basic Node", owner: "VDoc:content", body: "VDoc:content",
      paragraphize: true,
    },
    chapter: {
      range: "VDoc:Chapter", owner: "VDoc:content", body: "VDoc:content", rest: "dc:title",
      comment: "Numbered, titled chapter",
    },
    p: {
      range: "VDoc:Paragraph", owner: "VDoc:content", body: "VDoc:content",
      comment: "Vertically segmented paragraph",
    },
    c: {
      range: "VDoc:CharacterData", owner: "VDoc:content", body: "VDoc:content",
      rest: "VDoc:language", comment: "Character data",
    },
    bulleted: {
      range: "VDoc:BulletList", owner: "VDoc:content", body: "VDoc:entries",
      comment: "Bulleted list",
    },
    numbered: {
      range: "VDoc:NumberedList", owner: "VDoc:content", body: "VDoc:entries",
      comment: "Numbered list",
    },
    table: {
      range: "VDoc:Table", owner: "VDoc:content", body: "VDoc:headers", rest: "VDoc:lookup",
      comment: "Table",
    },
    header: {
      range: "VDoc:Header", owner: "VDoc:entries", body: "VDoc:content", rest: "VDoc:cell",
      comment: "Header",
    },
    data: {
      range: null, owner: null, body: null,
      comment: "Hidden data",
    },
  },
});
