const htmlSpecBase = "https://html.spec.whatwg.org/multipage/";

module.exports = {
  prefix: "vdoc",
  prefixIRI: "https://valospace.org/vdoc#",

  prefixes: {
    dc: "http://purl.org/dc/elements/1.1/",
    owl: "http://www.w3.org/2002/07/owl#",
    rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    rdfs: "http://www.w3.org/2000/01/rdf-schema#",
    vdoc: "https://valospace.org/vdoc#",
  },

  context: {
    a: { "@id": "rdf:type", "@type": "@id" },
    "vdoc:content": {
      "@id": "https://valospace.org/vdoc#content", "@container": "@list",
    },
    "vdoc:words": {
      "@id": "https://valospace.org/vdoc#words", "@container": "@list",
    },
    "vdoc:entries": {
      "@id": "https://valospace.org/vdoc#entries", "@container": "@list",
    },
  },

  vocabulary: {
    Class: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "rdfs:Class",
      "rdfs:comment": "The class of classes which are specified by vdoc or a vdoc extension",
    },
    Property: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "rdf:Property",
      "rdfs:comment": "The class of properties which are specified by vdoc or a vdoc extension",
    },
    Node: { "rdf:type": "vdoc:Class",
      "rdfs:comment": "A document tree Node",
    },
    resourceId: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "xsd:string",
      "rdfs:comment": "The resource identifier of a resource node",
    },
    content: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:List",
      "rdfs:comment": "The primary visible content of a Node",
    },
    words: { "rdf:type": "vdoc:Property",
      "rdfs:subPropertyOf": "vdoc:content",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:List",
      "rdfs:comment": "A visible list of visually separate words",
    },
    entries: { "rdf:type": "vdoc:Property",
      "rdfs:subPropertyOf": "vdoc:content",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:List",
      "rdfs:comment": "A visible list of vertically or horizontally segmented entries",
    },
    lookup: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "rdfs:comment": "A reference to a lookup structure for string literal entries",
    },
    wide: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "rdfs:comment": "Marks the node content as being wide",
    },
    tall: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "rdfs:comment": "Marks the node content as being tall",
    },
    Chapter: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A titled, possibly numbered chapter document node",
    },
    BulletList: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A bullet list document node",
    },
    NumberedList: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A numbered list document node",
    },
    Table: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A two-dimensional table document node",
    },
    Header: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A table cross-entry-section header node",
    },
    headers: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:Table", "rdfs:range": "rdfs:List",
      "rdfs:comment": "A list of table cross-entry-section headers",
    },
    cell: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:Header", "rdfs:range": "rdfs:List",
      "rdfs:comment": "The template for building cell content using content selectors",
    },
    ContentSelector: { "rdf:type": "vdoc:Class",
      "rdfs:comment": "The class of selectors with explicit meaning for selecting content",
    },
    selectKey: { "rdf:type": "vdoc:ContentSelector",
      "rdfs:comment": "A content selector literal denoting the entry lookup key",
    },
    selectValue: { "rdf:type": "vdoc:ContentSelector",
      "rdfs:comment": "A content selector literal denoting the whole entry value",
    },
    selectField: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "rdfs:Resource", "rdfs:range": "rdfs:Literal",
      "rdfs:comment": "A content selector for the entry field denoted by the object of this triple",
    },
    CharacterData: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A character data document node",
    },
    language: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:CharacterData", "rdfs:range": "rdfs:Resource",
      "rdfs:comment": "The language of the character data content",
    },
    Reference: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A reference document node",
    },
    ContextPath: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Node",
      "rdfs:comment": "A context-based path document node",
    },
    context: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:ContextPath", "rdfs:range": "rdfs:Resource",
      "rdfs:comment": "Non-visible context base (absolute or relative to current base)",
    },
    ContextBase: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:ContextPath",
      "rdfs:comment": "A context base setting document node",
    },
    HTMLElementProperty: { "rdf:type": "vdoc:Class",
      "rdfs:subClassOf": "vdoc:Property",
      "rdfs:comment":
`The class of vdoc properties which directly inherit the semantics of a specific HTML5 element`,
    },
    elementName: { "rdf:type": "vdoc:Property",
      "rdfs:domain": "vdoc:HTMLElementProperty", "rdfs:range": "xsd:string",
      "rdfs:comment": "The name of the html element associated with this property",
    },
    em: { "rdf:type": "vdoc:HTMLElementProperty",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "vdoc:elementName": "em",
      "vdoc:elementSpec": `${htmlSpecBase}text-level-semantics.html#the-em-element`,
      "rdfs:comment": "Node content is <em>emphasised</em>",
    },
    strong: { "rdf:type": "vdoc:HTMLElementProperty",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "vdoc:elementName": "strong",
      "vdoc:elementSpec": `${htmlSpecBase}text-level-semantics.html#the-strong-element`,
      "rdfs:comment": "Node content is <strong>strong</strong>",
    },
    ins: { "rdf:type": "vdoc:HTMLElementProperty",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "vdoc:elementName": "ins",
      "vdoc:elementSpec": `${htmlSpecBase}edits.html#the-ins-element`,
      "rdfs:comment": "Node content is an <ins>insertion</ins>",
    },
    del: { "rdf:type": "vdoc:HTMLElementProperty",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "vdoc:elementName": "del",
      "vdoc:elementSpec": `${htmlSpecBase}edits.html#the-del-element`,
      "rdfs:comment": "Node content is <del>deleted</del>",
    },
    quote: { "rdf:type": "vdoc:HTMLElementProperty",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "vdoc:elementName": "quote",
      "vdoc:elementSpec": `${htmlSpecBase}text-level-semantics.html#the-q-element`,
      "rdfs:comment": "Node content is <q>quoted</q>",
    },
    blockquote: { "rdf:type": "vdoc:HTMLElementProperty",
      "rdfs:domain": "vdoc:Node", "rdfs:range": "rdfs:Resource",
      "vdoc:elementName": "blockquote",
      "vdoc:elementSpec": `${htmlSpecBase}grouping-content.html#the-blockquote-element`,
      "rdfs:comment": "Node content is <blockquote>block quoted</blockquote>",
    },
  },

  extractionRules: {
    "": {
      comment: "Basic Node", owner: "vdoc:content", body: "vdoc:content",
    },
    chapter: {
      range: "vdoc:Chapter", owner: "vdoc:content", body: "vdoc:content", rest: "dc:title",
      comment: "Numbered, titled chapter",
    },
    c: {
      range: "vdoc:CharacterData", owner: "vdoc:content", body: "vdoc:content",
      rest: "vdoc:language", comment: "Character data",
    },
    bulleted: {
      range: "vdoc:BulletList", owner: "vdoc:content", body: "vdoc:entries",
      comment: "Bulleted list",
    },
    numbered: {
      range: "vdoc:NumberedList", owner: "vdoc:content", body: "vdoc:entries",
      comment: "Numbered list",
    },
    table: {
      range: "vdoc:Table", owner: "vdoc:content", body: "vdoc:headers", rest: "vdoc:lookup",
      comment: "Table",
    },
    header: {
      range: "vdoc:Header", owner: "vdoc:entries", body: "vdoc:content", rest: "vdoc:cell",
      comment: "Header",
    },
    data: {
      range: null, owner: null, body: null,
      comment: "Hidden data",
    },
  },
};
